[options]
; --- Database ---
db_host = localhost
db_port = 5434
db_user = odoo
db_password = Tibebu13d2144@
db_name = odoo17

; --- Server ---
addons_path = C:\Users\Tibebu.teferi\Downloads\odoo-17.0\odoo-17.0\addons,C:\Users\Tibebu.teferi\Downloads\odoo-17.0\odoo-17.0\odoo\addons
http_port = 8069

; --- Security ---
admin_passwd = 13d2144

; --- Logging ---
log_level = info
